/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
//importar paquetes necesarios
import com.mycompany.bdhotel.RegistroClientes;
import com.mycompany.bdhotel.RegistroHabitaciones;
import com.mycompany.bdhotel.RegistroReservas;

/**
 *
 * @author agseb
 */
public class vistaHotel extends javax.swing.JFrame {

    /**
     * Creates new form vistaColegio
     */
    public vistaHotel() {
        initComponents();
        this.setLocationRelativeTo(null);

        RegistroClientes objetoClientes = new RegistroClientes();
        objetoClientes.MostrarClientes(tbListaClientes);
        RegistroHabitaciones objetoHabitaciones = new RegistroHabitaciones();
        objetoHabitaciones.MostrarHabitaciones(tbListaHabitaciones);
        RegistroReservas objetoReservas = new RegistroReservas();
        objetoReservas.MostrarReservas(tbListaReservas1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        AvisoPrincipalHabitaciones = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idHabitaciontxt1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tipoHabitaciontxt1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        precioHabitxt1 = new javax.swing.JTextField();
        btnGuardarHab = new javax.swing.JButton();
        btnModificarHab = new javax.swing.JButton();
        btnEliminarHab = new javax.swing.JButton();
        txtBuscarHab = new javax.swing.JTextField();
        btnBuscarHab = new javax.swing.JButton();
        btnLimpiarHab = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListaHabitaciones = new javax.swing.JTable();
        AvisoPrincipalHabitaciones2 = new javax.swing.JLabel();
        DescripcionHabtxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        AvisoPrincipalRes = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idReservatxt1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        NdocuRestxt1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TipHabRestxt1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        DiasHostxt1 = new javax.swing.JTextField();
        btnGuardarRes = new javax.swing.JButton();
        btnModificarRes = new javax.swing.JButton();
        btnEliminarRes = new javax.swing.JButton();
        txtBuscarRes = new javax.swing.JTextField();
        btnBuscarRes = new javax.swing.JButton();
        btnLimpiarRes = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbListaReservas1 = new javax.swing.JTable();
        AvisoPrincipalRes2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        AvisoPrincipal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cctxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apetxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        celtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dirtxt = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaClientes = new javax.swing.JTable();
        AvisoPrincipal1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setForeground(new java.awt.Color(0, 102, 102));

        AvisoPrincipalHabitaciones.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        AvisoPrincipalHabitaciones.setForeground(new java.awt.Color(255, 204, 0));
        AvisoPrincipalHabitaciones.setText("habitaciones hotel La estancia");

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()+2f));
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("ID Habitacion");

        idHabitaciontxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idHabitaciontxt1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Tipo Habitacion");

        jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getSize()+2f));
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Descripción");

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getSize()+2f));
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Precio");

        precioHabitxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioHabitxt1ActionPerformed(evt);
            }
        });

        btnGuardarHab.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardarHab.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnGuardarHab.setText("Guardar");
        btnGuardarHab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarHabActionPerformed(evt);
            }
        });

        btnModificarHab.setBackground(new java.awt.Color(204, 255, 204));
        btnModificarHab.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnModificarHab.setText("Modificar");
        btnModificarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarHabActionPerformed(evt);
            }
        });

        btnEliminarHab.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminarHab.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnEliminarHab.setText("Eliminar");
        btnEliminarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHabActionPerformed(evt);
            }
        });

        txtBuscarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarHabActionPerformed(evt);
            }
        });

        btnBuscarHab.setBackground(new java.awt.Color(204, 255, 204));
        btnBuscarHab.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnBuscarHab.setText("Buscar");
        btnBuscarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHabActionPerformed(evt);
            }
        });

        btnLimpiarHab.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        btnLimpiarHab.setText("Limpiar");
        btnLimpiarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarHabActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Consultar Habitacion Tipo");

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbListaHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbListaHabitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaHabitacionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbListaHabitaciones);

        AvisoPrincipalHabitaciones2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        AvisoPrincipalHabitaciones2.setForeground(new java.awt.Color(255, 204, 0));
        AvisoPrincipalHabitaciones2.setText("Listado de habitaciones");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(AvisoPrincipalHabitaciones2)))
                .addGap(0, 247, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tipoHabitaciontxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(idHabitaciontxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(precioHabitxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(DescripcionHabtxt)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtBuscarHab, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnGuardarHab)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnModificarHab)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminarHab)
                                    .addComponent(btnBuscarHab)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(AvisoPrincipalHabitaciones))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnLimpiarHab, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(637, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AvisoPrincipalHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idHabitaciontxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoHabitaciontxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(DescripcionHabtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioHabitxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarHab)
                    .addComponent(btnEliminarHab)
                    .addComponent(btnGuardarHab))
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarHab, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarHab))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarHab, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(AvisoPrincipalHabitaciones2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Habitaciones", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        AvisoPrincipalRes.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        AvisoPrincipalRes.setForeground(new java.awt.Color(255, 204, 0));
        AvisoPrincipalRes.setText("reservas hotel La estancia");

        jLabel12.setFont(jLabel12.getFont().deriveFont(jLabel12.getFont().getSize()+2f));
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("ID Reserva");

        idReservatxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idReservatxt1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("N Documento");

        jLabel15.setFont(jLabel15.getFont().deriveFont(jLabel15.getFont().getSize()+2f));
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Tipo Habitación:");

        TipHabRestxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipHabRestxt1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(jLabel16.getFont().deriveFont(jLabel16.getFont().getSize()+2f));
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("Dias Hospedaje:");

        DiasHostxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasHostxt1ActionPerformed(evt);
            }
        });

        btnGuardarRes.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardarRes.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnGuardarRes.setText("Guardar");
        btnGuardarRes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarResActionPerformed(evt);
            }
        });

        btnModificarRes.setBackground(new java.awt.Color(204, 255, 204));
        btnModificarRes.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnModificarRes.setText("Modificar");
        btnModificarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarResActionPerformed(evt);
            }
        });

        btnEliminarRes.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminarRes.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnEliminarRes.setText("Eliminar");
        btnEliminarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarResActionPerformed(evt);
            }
        });

        txtBuscarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarResActionPerformed(evt);
            }
        });

        btnBuscarRes.setBackground(new java.awt.Color(204, 255, 204));
        btnBuscarRes.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnBuscarRes.setText("Buscar");
        btnBuscarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarResActionPerformed(evt);
            }
        });

        btnLimpiarRes.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        btnLimpiarRes.setText("Limpiar");
        btnLimpiarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarResActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("Consultar Cliente por numero de documento");

        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbListaReservas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbListaReservas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaReservas1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbListaReservas1);

        AvisoPrincipalRes2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        AvisoPrincipalRes2.setForeground(new java.awt.Color(255, 204, 0));
        AvisoPrincipalRes2.setText("Listado de Reservas");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(AvisoPrincipalRes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NdocuRestxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idReservatxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TipHabRestxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DiasHostxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtBuscarRes, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarRes))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnGuardarRes)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarRes)))
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarRes))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnLimpiarRes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AvisoPrincipalRes2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AvisoPrincipalRes)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(idReservatxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NdocuRestxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipHabRestxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiasHostxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarRes)
                            .addComponent(btnEliminarRes)
                            .addComponent(btnGuardarRes))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarRes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarRes))
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarRes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(AvisoPrincipalRes2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(475, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reservas", jPanel5);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        AvisoPrincipal.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        AvisoPrincipal.setForeground(new java.awt.Color(255, 204, 0));
        AvisoPrincipal.setText("Clientes hotel La estancia");

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+2f));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("ID Cliente");

        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("N CC");

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+2f));
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Nombres:");

        nomtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomtxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+2f));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Apellidos:");

        apetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apetxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Celular");

        celtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celtxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Direccion");

        btnGuardar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(204, 255, 204));
        btnModificar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(204, 255, 204));
        btnBuscar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Consultar cliente por numero de documento");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListaClientes);

        AvisoPrincipal1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        AvisoPrincipal1.setForeground(new java.awt.Color(255, 153, 0));
        AvisoPrincipal1.setText("Listado de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(celtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dirtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(btnLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(AvisoPrincipal)
                                .addGap(190, 190, 190)
                                .addComponent(AvisoPrincipal1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AvisoPrincipal)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(AvisoPrincipal1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(celtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 552, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Modificar registros de la tabla estudiantes
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        RegistroClientes objetoestudiante = new RegistroClientes();
        objetoestudiante.ModificarClientes(idtxt, cctxt, nomtxt,apetxt, celtxt, dirtxt);

        objetoestudiante.MostrarClientes(tbListaClientes);
    }//GEN-LAST:event_btnModificarActionPerformed
    // Eliminar registros de la tabla estudiantes
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        RegistroClientes objetoestudiante = new RegistroClientes();
        objetoestudiante.EliminarEstudiante(idtxt);
        objetoestudiante.MostrarClientes(tbListaClientes);

    }//GEN-LAST:event_btnEliminarActionPerformed

    //Buscar registros en la tabla estudiantes
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        RegistroClientes objetoestudiante = new RegistroClientes();
        objetoestudiante.MostrarClientes(tbListaClientes);
        objetoestudiante.BuscarCliente(tbListaClientes, txtBuscar);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        RegistroClientes objetoestudiante = new RegistroClientes();
        objetoestudiante.insertarCliente(cctxt, nomtxt,apetxt, celtxt, dirtxt);

        objetoestudiante.MostrarClientes(tbListaClientes);
    }//GEN-LAST:event_btnGuardarActionPerformed
    //evento para mostrar el listado con los estudiantes
    private void tbListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaClientesMouseClicked
        // TODO add your handling code here:
        RegistroClientes objetoestudiante = new RegistroClientes();
        objetoestudiante.SeleccionarCliente(tbListaClientes, idtxt,cctxt, nomtxt,apetxt, celtxt, dirtxt);

    }//GEN-LAST:event_tbListaClientesMouseClicked

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    private void nomtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomtxtActionPerformed

    private void apetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apetxtActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void celtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celtxtActionPerformed

    private void idHabitaciontxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idHabitaciontxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idHabitaciontxt1ActionPerformed

    private void DescripcionHabtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionHabtxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionHabtxt1ActionPerformed

    private void precioHabitxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioHabitxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioHabitxt1ActionPerformed

    private void btnGuardarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarHabActionPerformed
        // TODO add your handling code here:

        RegistroHabitaciones objetoHabitaciones = new RegistroHabitaciones();
        objetoHabitaciones.insertarHabitaciones(idHabitaciontxt1, tipoHabitaciontxt1, DescripcionHabtxt, precioHabitxt1);
        objetoHabitaciones.MostrarHabitaciones(tbListaHabitaciones);

    }//GEN-LAST:event_btnGuardarHabActionPerformed

    private void btnModificarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarHabActionPerformed
        // TODO add your handling code here:
        RegistroHabitaciones objetoHabitaciones = new RegistroHabitaciones();
        objetoHabitaciones.ModificarHabitaciones(idHabitaciontxt1, tipoHabitaciontxt1, DescripcionHabtxt, precioHabitxt1);
        objetoHabitaciones.MostrarHabitaciones(tbListaHabitaciones);

    }//GEN-LAST:event_btnModificarHabActionPerformed

    private void btnEliminarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHabActionPerformed
        // TODO add your handling code here:
        RegistroHabitaciones objetoHabitaciones = new RegistroHabitaciones();
        objetoHabitaciones.EliminarHabitacion(idHabitaciontxt1);
        objetoHabitaciones.MostrarHabitaciones(tbListaHabitaciones);
    }//GEN-LAST:event_btnEliminarHabActionPerformed

    private void txtBuscarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarHabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarHabActionPerformed

    private void btnBuscarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHabActionPerformed
        // TODO add your handling code here:
        RegistroHabitaciones objetoHabitaciones = new RegistroHabitaciones();
        objetoHabitaciones.MostrarHabitaciones(tbListaHabitaciones);
        objetoHabitaciones.BuscarHabitacion(tbListaHabitaciones,txtBuscarHab);
        //

    }//GEN-LAST:event_btnBuscarHabActionPerformed

    private void btnLimpiarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarHabActionPerformed
        // TODO add your handling code here:
        limpiarHabitacion();
    }//GEN-LAST:event_btnLimpiarHabActionPerformed

    private void tbListaHabitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaHabitacionesMouseClicked
        // TODO add your handling code here:
        RegistroHabitaciones objetoHabitaciones = new RegistroHabitaciones();
        objetoHabitaciones.SeleccionarHabitaciones(tbListaHabitaciones,idHabitaciontxt1,tipoHabitaciontxt1,DescripcionHabtxt,precioHabitxt1);

    }//GEN-LAST:event_tbListaHabitacionesMouseClicked

    private void idReservatxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idReservatxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idReservatxt1ActionPerformed

    private void TipHabRestxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipHabRestxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipHabRestxt1ActionPerformed

    private void DiasHostxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasHostxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiasHostxt1ActionPerformed

    private void btnGuardarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarResActionPerformed
        // TODO add your handling code here:
        RegistroReservas objetoReservas = new RegistroReservas();
        objetoReservas.InsertarReservas(idReservatxt1,NdocuRestxt1,TipHabRestxt1,DiasHostxt1);
        objetoReservas.MostrarReservas(tbListaReservas1);
    }//GEN-LAST:event_btnGuardarResActionPerformed

    private void btnModificarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarResActionPerformed
        // TODO add your handling code here:
        RegistroReservas objetoReservas = new RegistroReservas();
        objetoReservas.ModificarReserva(idReservatxt1,NdocuRestxt1,TipHabRestxt1,DiasHostxt1);
        objetoReservas.MostrarReservas(tbListaReservas1);
    }//GEN-LAST:event_btnModificarResActionPerformed

    private void btnEliminarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarResActionPerformed
        // TODO add your handling code here:
        RegistroReservas objetoReservas = new RegistroReservas();
        objetoReservas.EliminarReserva(idReservatxt1);
        objetoReservas.MostrarReservas(tbListaReservas1);
    }//GEN-LAST:event_btnEliminarResActionPerformed

    private void txtBuscarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarResActionPerformed

    private void btnBuscarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarResActionPerformed
        // TODO add your handling code here:

        RegistroReservas objetoReservas = new RegistroReservas();
        objetoReservas.MostrarReservas(tbListaReservas1);
        objetoReservas.BuscarReserva(tbListaReservas1,txtBuscarRes);
        System.out.printf("Se activo boton");

    }//GEN-LAST:event_btnBuscarResActionPerformed

    private void btnLimpiarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarResActionPerformed
        // TODO add your handling code here:
        limpiarReserva();
    }//GEN-LAST:event_btnLimpiarResActionPerformed

    private void tbListaReservas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaReservas1MouseClicked
        // TODO add your handling code here:
        RegistroReservas objetoReservas = new RegistroReservas();
        objetoReservas.SeleccionarReserva(tbListaReservas1, idReservatxt1,NdocuRestxt1,TipHabRestxt1,DiasHostxt1);
    }//GEN-LAST:event_tbListaReservas1MouseClicked


    private void limpiar(){
        idtxt.setText("");
        cctxt.setText("");
        nomtxt.setText("");
        apetxt.setText("");
        celtxt.setText("");
        dirtxt.setText("");
        RegistroHabitaciones objetoHabitaciones = new RegistroHabitaciones();
        objetoHabitaciones.MostrarHabitaciones(tbListaHabitaciones);
    }
    private void limpiarHabitacion(){
        idHabitaciontxt1.setText("");
        tipoHabitaciontxt1.setText("");
        DescripcionHabtxt.setText("");
        precioHabitxt1.setText("");
        RegistroHabitaciones objetoHabitaciones = new RegistroHabitaciones();
        objetoHabitaciones.MostrarHabitaciones(tbListaHabitaciones);
    }

    private void limpiarReserva(){
        idReservatxt1.setText("");
        NdocuRestxt1.setText("");
        TipHabRestxt1.setText("");
        DiasHostxt1.setText("");
        RegistroReservas objetoReservas = new RegistroReservas();
        objetoReservas.MostrarReservas(tbListaReservas1);
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvisoPrincipal;
    private javax.swing.JLabel AvisoPrincipal1;
    private javax.swing.JLabel AvisoPrincipalHabitaciones;
    private javax.swing.JLabel AvisoPrincipalHabitaciones2;
    private javax.swing.JLabel AvisoPrincipalRes;
    private javax.swing.JLabel AvisoPrincipalRes2;
    private javax.swing.JTextField DescripcionHabtxt;
    private javax.swing.JTextField DiasHostxt1;
    private javax.swing.JTextField NdocuRestxt1;
    private javax.swing.JTextField TipHabRestxt1;
    private javax.swing.JTextField apetxt;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarHab;
    private javax.swing.JButton btnBuscarRes;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarHab;
    private javax.swing.JButton btnEliminarRes;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarHab;
    private javax.swing.JButton btnGuardarRes;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnLimpiarHab;
    private javax.swing.JButton btnLimpiarRes;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarHab;
    private javax.swing.JButton btnModificarRes;
    private javax.swing.JTextField cctxt;
    private javax.swing.JTextField celtxt;
    private javax.swing.JTextField dirtxt;
    private javax.swing.JTextField idHabitaciontxt1;
    private javax.swing.JTextField idReservatxt1;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nomtxt;
    private javax.swing.JTextField precioHabitxt1;
    private javax.swing.JTable tbListaClientes;
    private javax.swing.JTable tbListaHabitaciones;
    private javax.swing.JTable tbListaReservas1;
    private javax.swing.JTextField tipoHabitaciontxt1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarHab;
    private javax.swing.JTextField txtBuscarRes;
    // End of variables declaration//GEN-END:variables
}
